"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "${time}${custom.arch}$all"

[cmd_duration]
min_time = 5000
show_milliseconds = true

[directory]
truncation_symbol = "…/"

[status]
disabled = false

[custom.arch]
description = "shows the CPU architecture"
when = "true"
command = "uname -m"

[time]
disabled = false
format = '[$time]($style) '

