[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>(quickrun)'
hook_add = '''
    nmap <Leader>r <Plug>(quickrun)
    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"

    let g:quickrun_config = {
        \ '_': {
        \   'runner': 'vimproc',
        \   'runner/vimproc/updatetime': 100
        \ }
        \ }
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_add = '''
    nmap <Leader>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'gregsexton/gitv'
depends = ['tpope/vim-fugitive']
on_cmd = ['Gitv']


### Filetype Specific
# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# Markdown
[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']


### C++
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
hook_add = '''
    let g:clang_c_options = '-std=c11'
    let g:clang_cpp_options = '-std=c++11 -stdlib=libc++ -pedantic-errors'
'''

[[plugins]]
repo = 'kana/vim-altr'
on_ft = ['c', 'cpp']


### Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['davidhalter/jedi-vim']
on_ft = ['python', 'python3', 'djangohtml']
hook_source = '''
    if jedi#init_python()
        function! s:jedi_auto_force_py_version() abort
            let major_version = pyenv#python#get_internal_major_version()
            call jedi#force_py_version(major_version)
        endfunction
        augroup vim-pyenv-custom-augroup
            autocmd! *
            autocmd vim-pyenv-activate-post * call s:jedi_auto_force_py_version()
            autocmd vim-pyenv-deactivate-post * call s:jedi_auto_force_py_version()
        augroup END
    endif
'''

[[plugins]]
repo = 'nvie/vim-flake8'
depends = ['vim-pyenv']
on_ft = ['python', 'python3', 'djangohtml']


### JavaScript
[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
# TODO: on_ft ?


### Ruby
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby']


### Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
