[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>(quickrun)'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']

[[plugins]]
repo = 'gregsexton/gitv'
depends = ['tpope/vim-fugitive']
on_cmd = ['Gitv']


### Filetype Specific
# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# Markdown
[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']


### C++
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'kana/vim-altr'
on_ft = ['c', 'cpp']


### Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['davidhalter/jedi-vim']
on_ft = ['python', 'python3', 'djangohtml']

[[plugins]]
repo = 'nvie/vim-flake8'
depends = ['vim-pyenv']
on_ft = ['python', 'python3', 'djangohtml']


### JavaScript
[[plugins]]
repo = 'mustache/vim-mustache-handlebars'
# TODO: on_ft ?


### Ruby
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby']


### Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
